### ISSUE TITLE
not working with reanimated

### ISSUE THREAD

**Issue by Bayramito** [WadhahEssam/react-native-theme-switch-animation#13]
Somehow does not work with when Reanimated 3.14.0 installed

**Comment by WadhahEssam** [comment]
Thank you for pointing that, will test it when I get the time

**Comment by Bayramito** [comment]
> Thank you for pointing that, will test it when I get the time

thank you.. i hope you fix it soon

**Comment by WadhahEssam** [comment]
https://github.com/user-attachments/assets/bfd42e58-03be-47b4-92a5-9371defb1f9c


tested it works fine with latest 3.15, this could be either problem with reanimated 3.14 in that case you can upgrade it or use 4.10 since it is the latest expo supported version. or it could be some build issue that is not related.
