### ISSUE TITLE
Feature request: expo config plugin

### ISSUE THREAD

**Issue by gorbypark** [WadhahEssam/react-native-theme-switch-animation#5]
Hello!  Thanks for the great library, it works really quite magically! 
 
I was wondering if you have considered releasing an expo config plugin for it?  It would make keeping apps in sync with expo versions much easier.  Currently (if I am not mistaken), if you use expo prebuild on an app, it exposes the android and iOS folders, which this library then "modifies" by linking against.  Once anything has "modified" the android or ios folders, upgrading to future expo versions is going to be a headache.  A config plugin would in the end give the same results but allow users to not have "modified" android/ios folders, allowing a much easier upgrade path.

**Comment by WadhahEssam** [comment]
@gorbypark Hello gorbypark thanks for your support 🙏. you don't need expo config plugin for this library because it doesn't need any modifications to your project's ios/android directories.

the libraries that need config plugin are the ones that usually need ios/android directories change like adding something to build.gradle/AppDelegate.mm/MainApplication.java or any other file. which this library doesn't need.

**Comment by gorbypark** [comment]
Aha!  I didn’t realize that.  Thanks again for the great library!
